
// function to give size of linked list ..............

// function to print linked list ..............

// function to add in front of linked list ..........

// function to insert at index ........

// function to print element at index ............

// function to delete element at index .....
